### ISSUE TITLE
The Minskins 14-12

### ISSUE THREAD

**Issue by Bismarck-GM** [carlosveigadev/weather-by-gifs#2]
### This deserves 69 stars
(Count them they're all there)

⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐ 

GIVE ME THEM ALL GIFS:

![](https://media.giphy.com/media/3o6ZtpKqKhFZADpfZm/giphy.gif)

**Comment by carlosveigadev** [comment]
Thanks guys!

![dance](https://media.giphy.com/media/ta0ejaLmjTqo6inVbh/giphy.gif)
